-- CreateTable
CREATE TABLE `colaboradores` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `sobrenome` VARCHAR(100) NOT NULL,
    `idade` INTEGER NOT NULL,
    `dataNascimento` DATETIME(3) NOT NULL,
    `numero` VARCHAR(20) NOT NULL,
    `setor` VARCHAR(100) NOT NULL,
    `cargo` VARCHAR(100) NOT NULL,
    `cpf` CHAR(14) NOT NULL,
    `identidade` VARCHAR(20) NOT NULL,
    `pis` VARCHAR(20) NOT NULL,
    `ctps` VARCHAR(20) NOT NULL,
    `cnhNumero` VARCHAR(20) NOT NULL,
    `cnhVencimento` DATETIME(3) NOT NULL,
    `endereco` VARCHAR(255) NOT NULL,
    `bairro` VARCHAR(100) NOT NULL,
    `cidade` VARCHAR(100) NOT NULL,
    `cep` CHAR(9) NOT NULL,
    `uf` CHAR(2) NOT NULL,
    `banco` VARCHAR(100) NOT NULL,
    `bancoNumero` VARCHAR(20) NOT NULL,
    `contaNumero` VARCHAR(20) NOT NULL,
    `agenciaNumero` VARCHAR(20) NOT NULL,
    `tipoVale` VARCHAR(50) NOT NULL,
    `vt1Valor` DOUBLE NOT NULL,
    `empresaAcess` VARCHAR(100) NOT NULL,
    `empresaRegistro` VARCHAR(100) NOT NULL,
    `empresaTrabalho` VARCHAR(100) NOT NULL,
    `tipo` VARCHAR(50) NOT NULL,
    `comissao` DOUBLE NOT NULL,
    `admissao` DATETIME(3) NOT NULL,
    `demissao` DATETIME(3) NULL,
    `oculto` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `colaboradores_cpf_key`(`cpf`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
